### ISSUE TITLE
Dual artifact for Reminder validation in Release 2017-05-15?

### ISSUE THREAD

**Issue by monze** [difi/vefa-ehf-postaward#216]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
In the newest release, the validation artifact for reminder in the zip file, exist as xsl here:
Source: https://github.com/difi/vefa-ehf-postaward/archive/2017-05-15.zip
Location of the compiled sch file in zip-file: vefa-ehf-postaward-2017-05-15\rules\ehf-reminder-1.1\xsl\NONAT-UBL-T17.xsl

The schematron source can also be found in the same zip-file here:
Location in zip-file: vefa-ehf-postaward-2017-05-15\rules\ehf-reminder-1.1\sch\NONAT-UBL-T17.sch

If we build the schematron source to an xslt (xsl) fil, we end up with a slight different version than the released 'NONAT-UBL-T17.xsl' file:
Location of the compiled sch file in zip-file: vefa-ehf-postaward-2017-05-15\rules\ehf-reminder-1.1\xsl\NONAT-UBL-T17.xsl

The two files have the same name, and it seems that they contain the same set of validations but the id and text of the validations seems to differ.

Is the xsl file or the sch file in the zip-file not updated? 

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
So, let me get an overview of this issue:

* Did we commit a new file for reminder during last development cycle? Yes
* Did we provide a describing commit message? [Yes](https://github.com/difi/vefa-ehf-postaward/commit/3c9373ab483ed933ec4194cc580ca0e14f716e58)
* Do we need to bump the version number of a document type whatever small change we make to the format? Yes
* Did we bump the version of Reminder? No
* Did we make available information in the release note of any changes to reminder? [No](https://vefa.difi.no/ehf/guide/release/2017-05-15/)
* Are we intentionally making changes to the validation rules without reporting it in the release note? No
* Did we remove the old XSLT file used for validation of reminder? No
* Are we using the Schematron file in the configuration? [No](https://github.com/difi/vefa-ehf-postaward/blob/master/rules/ehf-reminder-1.1/buildconfig.xml)

During the last few years has Difi put a lot of efforts into making sure the release of updated guides and validation artificats for our formats is performed more logical, clearly signaling changes, created tools to increase quality for every single release and in general tried to make EHF updates less painful due to the fact that we mainly perform four releases a year.

I've prepared a Schematron file for reminder to perform quality assurance (remember increase quality) when I find time later so we can make it the authoritative set rules when we are satisfied with the quality. As I were unable to finish this during the previous developement cycle, I added it to our repository because Git is extreamly good at keeping track of my files.

Based upon the above information, and the fact that this issue exists, I guess we've been unclear in some way regarding the file in question, and as I've problems seeing what we did wrong, can you please enlighten me so we can perform better next time we have artifacts not ready for release (oh yes, it's gonna happen again)?

**Comment by monze** [comment]
Hey Erlend

Thanks for the feedback.
I do agree that Difi put a lot of effort into making Schematrons and makes the releases as easy to use as possible. That is one of the reason why we take us the time to report our finding back to Difi.

But back to the issue.
For the following document packages, there exist two types of schematron artifacts, the .xsl files provided by PEPPOL.eu and .sch files which are Difi validation rules:
* ehf-catalogue-1.0
* ehf-catalogue-response-1.0
* ehf-creditnote-2.0
* ehf-despatch-advice-1.0
* ehf-invoice-2.0
* ehf-order-1.0
* ehf-order-response-1.0

But for 'ehf-reminder-1.1', peppol has no validation rules, so the validations are only provided by Difi. But the [buildfile](https://github.com/difi/vefa-ehf-postaward/blob/master/rules/ehf-reminder-1.1/buildconfig.xml) state that we must use the .xsl file and not the .sch (as I would have expected, since it is used in the other document packages).

So if I boils this down, the issue can be seen as a comment about that there exist two files, and a question about which one of them should be used.

But, as you point out, the build file point to the .xsl file, so I expect that this is the 'official' validation file for ehf-reminder.

Jacob Mogensen
mySupply ApS
Denmark
